# Generated by Django 5.2.8 on 2026-02-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("OWNER", "Owner"), ("TECH", "Technician")],
                        default="OWNER",
                        max_length=20,
                    ),
                ),
                (
                    "tech_level",
                    models.CharField(
                        choices=[
                            ("OSTA", "Master Technician"),
                            ("SABI", "Apprentice"),
                            ("NONE", "Not a Technician"),
                        ],
                        default="NONE",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
