# Generated by Django 5.2 on 2026-04-02 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="history",
            name="recipe",
        ),
        migrations.RemoveField(
            model_name="history",
            name="user",
        ),
        migrations.DeleteModel(
            name="Favorites",
        ),
        migrations.DeleteModel(
            name="History",
        ),
    ]
