# Generated by Django 5.2.8 on 2026-02-16 16:35

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="device_labels/"
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("raw_ocr_data", models.JSONField(blank=True, default=dict)),
                ("device_type", models.CharField(max_length=100)),
                ("specifications", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region="EG"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "calculated_total",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("is_paid", models.BooleanField(default=False)),
                ("pdf_copy", models.FileField(blank=True, null=True, upload_to="")),
                ("issued_date", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "tenant_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("shop_name", models.CharField(max_length=255)),
                ("owner_email", models.EmailField(max_length=254, unique=True)),
                ("preferences", models.JSONField(blank=True, default=dict)),
                (
                    "specialty",
                    models.CharField(
                        choices=[
                            ("electronics", "Electronics Repair"),
                            ("automotive", "Automotive Repair"),
                            ("general", "general repair"),
                        ],
                        default="electronics",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AudioItem",
            fields=[
                (
                    "item_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="shops.item",
                    ),
                ),
                ("firmware_version", models.CharField(blank=True, max_length=50)),
                ("case_serial", models.CharField(blank=True, max_length=50)),
            ],
            bases=("shops.item",),
        ),
        migrations.CreateModel(
            name="AutomotiveItem",
            fields=[
                (
                    "item_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="shops.item",
                    ),
                ),
                ("vin", models.CharField(blank=True, max_length=17, unique=True)),
                ("engine_type", models.CharField(blank=True, max_length=100)),
            ],
            bases=("shops.item",),
        ),
        migrations.CreateModel(
            name="ComputingItem",
            fields=[
                (
                    "item_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="shops.item",
                    ),
                ),
                ("processor", models.CharField(blank=True, max_length=100)),
                ("ram", models.CharField(blank=True, max_length=50)),
                ("gpu", models.CharField(blank=True, max_length=100)),
                ("storage", models.CharField(blank=True, max_length=50)),
            ],
            bases=("shops.item",),
        ),
        migrations.CreateModel(
            name="GamingItem",
            fields=[
                (
                    "item_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="shops.item",
                    ),
                ),
                ("storage_capacity", models.CharField(blank=True, max_length=50)),
                ("controller_type", models.CharField(blank=True, max_length=50)),
                ("firmware", models.CharField(blank=True, max_length=50)),
            ],
            bases=("shops.item",),
        ),
        migrations.CreateModel(
            name="MobileItem",
            fields=[
                (
                    "item_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="shops.item",
                    ),
                ),
                ("IMEI", models.CharField(blank=True, max_length=100)),
                ("battery_health", models.IntegerField(blank=True, null=True)),
                ("screen_type", models.CharField(blank=True, max_length=100)),
            ],
            bases=("shops.item",),
        ),
        migrations.AddField(
            model_name="item",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to="shops.customer",
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_method", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="shops.invoice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Technician",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=50)),
                (
                    "hourly_rate",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shops.tenant"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="item",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="shops.tenant",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shops.tenant"
            ),
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part_name", models.CharField(max_length=255)),
                ("stock_level", models.IntegerField(default=0)),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("reorder_point", models.IntegerField(default=5)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shops.tenant"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="customer",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customers",
                to="shops.tenant",
            ),
        ),
        migrations.CreateModel(
            name="WorkOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255, null=True)),
                ("diagnostic_data", models.JSONField(blank=True, default=dict)),
                (
                    "intake_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="work_orders/intake/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("diagnosing", "In Diagnosis"),
                            ("parts", "Waiting for Parts"),
                            ("ready", "Ready for Pickup"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_tech",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shops.technician",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_order",
                        to="shops.item",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shops.tenant"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_status", models.CharField(max_length=20)),
                ("new_status", models.CharField(max_length=20)),
                ("changed_at", models.DateField(auto_now_add=True)),
                (
                    "technician",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shops.technician",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="shops.workorder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_name", models.CharField(max_length=255)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shops.workorder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PartUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_used", models.IntegerField(default=1)),
                (
                    "price_at_use",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts_used",
                        to="shops.inventory",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shops.workorder",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="invoice",
            name="work_order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice",
                to="shops.workorder",
            ),
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_path", models.FileField(upload_to="work_orders/attachments/")),
                ("upload_type", models.CharField(max_length=50)),
                ("time_stamp", models.DateTimeField(auto_now_add=True)),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="shops.workorder",
                    ),
                ),
            ],
        ),
    ]
