# Generated by Django 5.2.8 on 2026-02-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="actiontoken",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
