# Generated by Django 5.2.8 on 2026-02-16 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeVideoItem",
            fields=[
                (
                    "item_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="shops.item",
                    ),
                ),
                (
                    "panel_type",
                    models.CharField(
                        choices=[("OLED", "OLED"), ("QLED", "QLED"), ("LED", "LED")],
                        max_length=4,
                    ),
                ),
                ("resolution_max", models.CharField(default="4K", max_length=20)),
                ("backlit_hours", models.PositiveIntegerField(default=0)),
                ("is_smart", models.BooleanField(default=True)),
            ],
            bases=("shops.item",),
        ),
        migrations.CreateModel(
            name="WearableItem",
            fields=[
                (
                    "item_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="shops.item",
                    ),
                ),
                (
                    "water_resistance_rating",
                    models.CharField(blank=True, max_length=50),
                ),
                ("battery_cycle_count", models.PositiveIntegerField(default=0)),
                ("firmware_version", models.CharField(blank=True, max_length=50)),
                (
                    "sensor_data",
                    models.JSONField(
                        default=dict, help_text="Store health for Heart Rate, GPS, etc."
                    ),
                ),
            ],
            bases=("shops.item",),
        ),
        migrations.AddField(
            model_name="inventory",
            name="barcode",
            field=models.CharField(
                db_index=True, default="TEMP_BARCODE", max_length=100, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="device_type",
            field=models.CharField(
                choices=[
                    ("COMP", "Computing"),
                    ("MOBL", "Mobile"),
                    ("GAME", "Gaming"),
                    ("AUDI", "Audio"),
                    ("WEAR", "Wearable"),
                    ("VIDO", "Home Video"),
                ],
                max_length=4,
            ),
        ),
        migrations.DeleteModel(
            name="AutomotiveItem",
        ),
    ]
