# Generated by Django 5.2.8 on 2026-02-19 18:38

import shops.models.auth
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0002_actiontoken_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actiontoken",
            name="expires_at",
            field=models.DateTimeField(default=shops.models.auth.get_default_expiry),
        ),
    ]
