# Generated by Django 5.2.8 on 2026-02-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0002_invitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="tech_level",
            field=models.CharField(
                choices=[
                    ("OSTA", "Master Technician"),
                    ("SABI", "Apprentice"),
                    ("NONE", "N/A"),
                ],
                default="NONE",
                max_length=10,
            ),
        ),
    ]
