# Generated by Django 5.2.8 on 2026-02-18 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0003_invitation_tech_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workorder",
            name="qr_code_key",
        ),
    ]
