# Generated by Django 5.2.8 on 2026-02-19 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0003_alter_actiontoken_expires_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inventory",
            old_name="base_price",
            new_name="cost_price",
        ),
        migrations.RenameField(
            model_name="inventory",
            old_name="part_name",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="inventory",
            name="reorder_point",
        ),
        migrations.RemoveField(
            model_name="inventory",
            name="stock_level",
        ),
        migrations.AddField(
            model_name="actiontoken",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("TECHNICIAN", "Technician"),
                    ("CUSTOMER", "Customer"),
                ],
                default="TECHNICIAN",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="actiontoken",
            name="tech_level",
            field=models.CharField(
                choices=[
                    ("OSTA", "Master Technician (Osta)"),
                    ("SABI", "Apprentice (Sabi)"),
                    ("NONE", "N/A"),
                ],
                default="NONE",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="inventory",
            name="product_type",
            field=models.CharField(
                choices=[("PART", "Repair Part"), ("RETAIL", "Retail Product")],
                default="RETAIL",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="retail_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="inventory",
            name="sku",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="inventory",
            name="specifications",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="inventory",
            name="stock_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="Invitation",
        ),
    ]
