# Generated by Django 5.2.8 on 2026-02-19 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0004_rename_base_price_inventory_cost_price_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="inventory",
            unique_together={("tenant", "sku")},
        ),
    ]
