# Generated by Django 5.2.8 on 2026-02-18 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_userprofile_tech_level"),
        ("shops", "0004_remove_workorder_qr_code_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="internal_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="workorder",
            name="part_quality",
            field=models.CharField(
                choices=[
                    ("original", "Original"),
                    ("high_copy", "High Copy"),
                    ("used_pull", "Used/Pull"),
                    ("none", "N/A"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="assigned_tech",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "TECH"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="authentication.userprofile",
            ),
        ),
    ]
