# Generated by Django 5.2.8 on 2026-02-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0005_workorder_internal_notes_workorder_part_quality_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="device_image",
        ),
        migrations.RemoveField(
            model_name="item",
            name="raw_ocr_data",
        ),
        migrations.AddField(
            model_name="item",
            name="brand",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="model",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
