# Generated by Django 5.2.8 on 2026-02-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0005_alter_inventory_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
