# Generated by Django 5.2.8 on 2026-02-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0006_tenant_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tenant",
            old_name="name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="tenant",
            name="last_name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
