# Generated by Django 5.2.8 on 2026-02-18 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0006_remove_item_device_image_remove_item_raw_ocr_data_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="model",
            new_name="model_name",
        ),
    ]
