# Generated by Django 5.2.8 on 2026-02-18 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0007_rename_model_item_model_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="deposit_paid",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="workorder",
            name="ticket_id",
            field=models.CharField(
                blank=True, editable=False, max_length=20, unique=True
            ),
        ),
    ]
