# Generated by Django 5.2.8 on 2026-02-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0007_rename_name_tenant_first_name_tenant_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actiontoken",
            name="tech_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OSTA", "Master Technician (Osta)"),
                    ("SABI", "Apprentice (Sabi)"),
                    ("NONE", "N/A"),
                ],
                default="NONE",
                max_length=10,
                null=True,
            ),
        ),
    ]
