# Generated by Django 5.2.8 on 2026-02-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0008_workorder_deposit_paid_workorder_ticket_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="brand",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="model_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="serial_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
