# Generated by Django 5.2.8 on 2026-02-21 11:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0008_alter_actiontoken_tech_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="actiontoken",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
