# Generated by Django 5.2.8 on 2026-02-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0009_actiontoken_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actiontoken",
            name="role",
            field=models.CharField(
                choices=[
                    ("OWNER", "Owner"),
                    ("TECH", "Technician"),
                    ("CUSTOMER", "Customer"),
                ],
                default="TECHNICIAN",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="actiontoken",
            name="token_type",
            field=models.CharField(
                choices=[
                    ("STAFF_INVITE", "Staff Invite"),
                    ("CUSTOMER_INVITE", "Customer Invite"),
                ],
                max_length=20,
            ),
        ),
    ]
