# Generated by Django 5.2.8 on 2026-02-21 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_initial"),
        ("shops", "0010_alter_actiontoken_role_alter_actiontoken_token_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workorder",
            name="assigned_tech",
        ),
        migrations.AddField(
            model_name="workorder",
            name="assigned_osta_tech",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "TECH", "tech_level": "SABI"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sabi_tasks",
                to="authentication.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="assigned_sabi_tech",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "TECH", "tech_level": "OSTA"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="osta_tasks",
                to="authentication.userprofile",
            ),
        ),
    ]
