# Generated by Django 5.2.8 on 2026-02-22 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0011_remove_workorder_assigned_tech_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("diagnosing", "In Diagnosis"),
                    ("parts", "Waiting for Parts"),
                    ("working", "working on device"),
                    ("ready", "Ready for Pickup"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
