# Generated by Django 5.2.8 on 2026-02-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0012_alter_workorder_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="low_stock_threshold",
            field=models.PositiveIntegerField(default=5),
        ),
    ]
