# Generated by Django 5.2.8 on 2026-02-23 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_initial"),
        ("shops", "0013_inventory_low_stock_threshold"),
    ]

    operations = [
        migrations.AddField(
            model_name="technician",
            name="profile",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="technician",
                to="authentication.userprofile",
            ),
        ),
    ]
