# Generated by Django 5.2.8 on 2026-02-23 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0015_service_standard_duration_worksession"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="work_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shops.workorder",
            ),
        ),
    ]
