# Generated by Django 5.2.8 on 2026-02-23 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0016_alter_service_work_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partusage",
            name="work_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parts_used_in",
                to="shops.workorder",
            ),
        ),
    ]
