# Generated by Django 5.2.8 on 2026-02-23 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0020_worksession_work_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worksession",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="session_service",
                to="shops.service",
            ),
        ),
    ]
