# Generated by Django 5.2.8 on 2026-02-24 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0021_alter_worksession_service"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("parts", "Spare Parts"),
                            ("labor", "Technician/Labor"),
                            ("rent", "Shop Rent"),
                            ("utilities", "Electricity/Internet"),
                            ("marketing", "Marketing/Ads"),
                            ("other", "Miscellaneous"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="shops.tenant",
                    ),
                ),
            ],
        ),
    ]
