# Generated by Django 5.2.8 on 2026-02-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0022_expense"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
